# Copyright 2021-2026 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Windows GitHub CI

on:
  pull_request:
    paths-ignore:
    - 'doc/**'
    - '*.md'
    - '*.pod'
    - 'README*'
    - 'funding.json'
    - 'LICENSE.txt'
    - 'VERSION.dat'
  push:
    paths-ignore:
    - 'doc/**'
    - '*.md'
    - '*.pod'
    - 'README*'
    - 'funding.json'
    - 'LICENSE.txt'
    - 'VERSION.dat'


permissions:
  contents: read

jobs:
  mingw64:
    strategy:
      matrix:
        platform:
        - arch: mingw64
          target: x86_64
            #  Avoid MINGW bug in headers. Remove when CI is upgraded.
          config: enable-demos -Wno-array-bounds
        - arch: mingw
          target: i686
          config: -Wno-array-bounds -Wno-stringop-overflow
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.platform.target }}-w64-mingw32-gcc
      CXX: ${{ matrix.platform.target }}-w64-mingw32-g++
      AR: ${{ matrix.platform.target }}-w64-mingw32-ar
      RANLIB: ${{ matrix.platform.target }}-w64-mingw32-ranlib
      RC: ${{ matrix.platform.target }}-w64-mingw32-windres
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: install MINGW64
      run: sudo apt-get install -y mingw-w64
    - name: config
      run: ./config ${{ matrix.platform.arch }}  --strict-warnings --banner=Configured ${{ matrix.platform.config }}
    - name: make
      run: make -j4 -s

